#!/usr/bin/env bash
# Record the P3 human loop again with ZERO tmux: the card runs on the ACP task
# executor (`HANGAR_TASK_EXECUTOR=acp`), the agent's Write lands as a
# `session/request_permission` attention row, Control Center renders the
# ADAPTER's own options (① Always Allow ② Allow ③ Reject), the operator rejects
# the primary path by digit, the agent falls back to the alternate path, the
# operator allows that one, and the transcript proves which path was written.
#
# Move 1 exit criterion (B), `docs/hangar/renovation/PLAN.md`. AskUserQuestion is
# not reachable under ACP (`claude-agent-acp` 0.23.1 passes
# `disallowedTools: ["AskUserQuestion"]`), so the pre-authorised fallback is a
# tool-permission approval: still a full structured round trip, still no tmux.
#
# Prereqs: the iso instance up under `env-acp.sh` (daemon on the ACP executor),
# a board whose LAST card carries the DBPATH brief and has never been run, and
# `CLAUDE_CODE_OAUTH_TOKEN` on the agent (an ACP task's adapter gets a scoped,
# EMPTY `CLAUDE_CONFIG_DIR`, so nothing else authenticates it).
#
# Usage: ISO=... WT=... CARD_DOWN=5 bash scripts/hangar/record-fullstack-p3-acp.sh
# Output: docs/hangar/proofs/fullstack/p3-acp-human-loop.{gif,mp4} + p3-acp-N-*.png
set -euo pipefail

ISO="${ISO:-/home/claude/ainb-e2e-home}"
WT="${WT:-$(cd "$(dirname "$0")/../.." && pwd)}"
# How many `Down` presses reach the brief's card from the top of the column.
CARD_DOWN="${CARD_DOWN:-5}"
BIN="$WT/ainb-tui/target/debug/ainb"
DAEMON="$WT/ainb-tui/target/debug/ainb-hangar-daemon"
PLUGINS="$WT/ainb-tui/dist/plugins"
OUT="$WT/docs/hangar/proofs/fullstack"
# No `exec`: the shell must survive `q` so the ground-truth script can run after.
LAUNCH="HOME='$ISO' TMUX_TMPDIR='$ISO/tmux' AINB_PLUGIN_ROOT='$PLUGINS' AINB_BIN='$BIN' AINB_HANGAR_DAEMON_BIN='$DAEMON' env -u AINB_HANGAR_HOME -u AINB_HOME -u TMUX -u TMUX_PANE '$BIN' tui"
# Reads the five clauses out of the store and the worktree rather than the
# screen. Lives in a helper so the tape's Type line carries no pattern that
# would match its own echo.
PROOF="$ISO/acp-proof/p3-acp-proof.sh"

for t in vhs ffmpeg sqlite3; do command -v "$t" >/dev/null || { echo "missing: $t" >&2; exit 2; }; done
[ -x "$BIN" ] || { echo "no ainb binary at $BIN" >&2; exit 2; }
[ -x "$PROOF" ] || { echo "no proof script at $PROOF" >&2; exit 2; }
[ -S "$ISO/.agents-in-a-box/hangar.sock" ] || { echo "iso daemon not running" >&2; exit 2; }
mkdir -p "$OUT"

DOWNS=""
for _ in $(seq 1 "$CARD_DOWN"); do DOWNS="${DOWNS}Down
Sleep 400ms
"; done

TAPE="$OUT/p3-acp-human-loop.tape"
cat > "$TAPE" <<EOF
# Generated by scripts/hangar/record-fullstack-p3-acp.sh. Baked paths are this host's.
Output p3-acp-human-loop.gif
Output p3-acp-human-loop.mp4
Set Shell "bash"
Set FontSize 13
Set Width 1800
Set Height 960
Set Padding 12
Set TypingSpeed 40ms

Hide
Type "$LAUNCH"
Enter
Wait+Screen@60s /navigate/
Show
Type "g"
Wait+Screen@30s /Settings/
Sleep 1s
Type "B"
Sleep 2s
$DOWNS
Sleep 2s
Screenshot p3-acp-1-board-card.png
Enter
Sleep 2s
Screenshot p3-acp-2-run-menu.png
Enter
Sleep 3s
Screenshot p3-acp-3-launched.png
Type "C"
Sleep 2s
Screenshot p3-acp-4-control-center-waiting.png
Wait+Screen@300s /Reject/
Sleep 2s
Screenshot p3-acp-5-ask-raised.png
Type "3"
Sleep 30s
Screenshot p3-acp-6-fallback-ask.png
Type "2"
Wait+Screen@180s /0 need you/
Sleep 2s
Screenshot p3-acp-7-answered-flip.png
Type "B"
Sleep 3s
Type "t"
Wait+Screen@60s /turn_completed/
Sleep 2s
Screenshot p3-acp-8-transcript-proof.png
Escape
Sleep 1s
Type "q"
Sleep 2s
Type "q"
Sleep 4s
Type "HOME='$ISO' bash $PROOF"
Enter
Wait+Screen@30s /final message/
Sleep 3s
Screenshot p3-acp-9-ground-truth.png
EOF

cd "$OUT"
rm -f p3-acp-human-loop.gif p3-acp-human-loop.mp4 p3-acp-[0-9]-*.png
VHS_NO_SANDBOX=true vhs "$TAPE"

# A gif vhs never finished encoding is TRUNCATED, not empty: measured here at
# exactly 768 KiB with no `;` trailer while the mp4 beside it was whole, which a
# `-s` check passes. Test the trailer byte, the one thing a complete GIF has.
gif_complete() {
  [ -s "$1" ] && [ "$(tail -c1 "$1" | od -An -tx1 | tr -d ' \n')" = "3b" ]
}
if ! gif_complete p3-acp-human-loop.gif && [ -s p3-acp-human-loop.mp4 ]; then
  echo "gif truncated or empty; regenerating from mp4" >&2
  ffmpeg -y -loglevel error -i p3-acp-human-loop.mp4 \
    -vf "fps=6,scale=1400:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=128[p];[s1][p]paletteuse=dither=bayer" \
    p3-acp-human-loop.gif
  command -v gifsicle >/dev/null && gifsicle -O3 --lossy=60 -o p3-acp-human-loop.gif p3-acp-human-loop.gif
fi

for f in p3-acp-human-loop.mp4 p3-acp-5-ask-raised.png p3-acp-7-answered-flip.png \
         p3-acp-8-transcript-proof.png p3-acp-9-ground-truth.png; do
  [ -s "$f" ] || { echo "artifact missing or empty: $f" >&2; exit 1; }
done
ls -la p3-acp-human-loop.gif p3-acp-human-loop.mp4 p3-acp-[0-9]-*.png
