//! Built-in keymap rows. Keep actions here, never in the renderer or CLI.

use super::events::AppEvent;
use super::keymap::{Binding, Chord, KeyAction, KeyContext, UiAction};

fn app(
    ctx: KeyContext,
    id: &'static str,
    chord: &str,
    event: AppEvent,
    doc: &'static str,
) -> Binding {
    Binding {
        id,
        ctx,
        chord: Chord::parse(chord).expect("built-in chord is valid"),
        action: KeyAction::App(event),
        doc,
    }
}

fn action(
    ctx: KeyContext,
    id: &'static str,
    chord: &str,
    action: KeyAction,
    doc: &'static str,
) -> Binding {
    Binding {
        id,
        ctx,
        chord: Chord::parse(chord).expect("built-in chord is valid"),
        action,
        doc,
    }
}

macro_rules! append_app_rows {
    ($rows:expr, $ctx:expr, $( $id:ident : $chord:literal => $event:expr ),+ $(,)?) => {
        $(
            $rows.push(app(
                $ctx.clone(),
                stringify!($id),
                $chord,
                $event,
                "Host keyboard action",
            ));
        )+
    };
}

macro_rules! append_action_rows {
    ($rows:expr, $ctx:expr, $( $id:ident : $chord:literal => $key_action:expr ),+ $(,)?) => {
        $(
            $rows.push(action(
                $ctx.clone(),
                stringify!($id),
                $chord,
                $key_action,
                "Host keyboard action",
            ));
        )+
    };
}

/// Canonical host-owned defaults. Component-owned New Session and PickRepo rows stay local.
#[must_use]
pub fn defaults() -> Vec<Binding> {
    use KeyContext as Context;

    let mut rows = vec![
        app(
            Context::ConfirmDialog,
            "previous",
            "left",
            AppEvent::ConfirmationPrev,
            "Select previous confirmation option",
        ),
        app(
            Context::ConfirmDialog,
            "toggle",
            "right",
            AppEvent::ConfirmationToggle,
            "Change confirmation selection",
        ),
        app(
            Context::ConfirmDialog,
            "toggle_tab",
            "tab",
            AppEvent::ConfirmationToggle,
            "Change confirmation selection",
        ),
        app(
            Context::ConfirmDialog,
            "confirm",
            "enter",
            AppEvent::ConfirmationConfirm,
            "Confirm dialog",
        ),
        app(
            Context::ConfirmDialog,
            "cancel",
            "esc",
            AppEvent::ConfirmationCancel,
            "Cancel dialog",
        ),
        app(
            Context::McpOverlay,
            "close",
            "esc",
            AppEvent::McpOverlayClose,
            "Close MCP pool",
        ),
        app(
            Context::McpOverlay,
            "close_q",
            "q",
            AppEvent::McpOverlayClose,
            "Close MCP pool",
        ),
        app(
            Context::McpOverlay,
            "close_p",
            "p",
            AppEvent::McpOverlayClose,
            "Close MCP pool",
        ),
        app(
            Context::McpOverlay,
            "previous",
            "up",
            AppEvent::McpOverlayPrev,
            "Previous MCP server",
        ),
        app(
            Context::McpOverlay,
            "previous_k",
            "k",
            AppEvent::McpOverlayPrev,
            "Previous MCP server",
        ),
        app(
            Context::McpOverlay,
            "next",
            "down",
            AppEvent::McpOverlayNext,
            "Next MCP server",
        ),
        app(
            Context::McpOverlay,
            "next_j",
            "j",
            AppEvent::McpOverlayNext,
            "Next MCP server",
        ),
        app(
            Context::McpOverlay,
            "refresh",
            "r",
            AppEvent::McpOverlayRefresh,
            "Refresh MCP pool",
        ),
        app(
            Context::McpOverlay,
            "stop_server",
            "s",
            AppEvent::McpOverlayStopServer,
            "Stop selected MCP server",
        ),
        app(
            Context::McpOverlay,
            "stop_daemon",
            "X",
            AppEvent::McpOverlayStopDaemon,
            "Stop MCP daemon",
        ),
        app(
            Context::McpOverlay,
            "import",
            "i",
            AppEvent::McpOverlayImport,
            "Import MCP configuration",
        ),
        app(
            Context::SessionContextMenu,
            "previous",
            "up",
            AppEvent::SessionContextPrev,
            "Previous context-menu item",
        ),
        app(
            Context::SessionContextMenu,
            "previous_k",
            "k",
            AppEvent::SessionContextPrev,
            "Previous context-menu item",
        ),
        app(
            Context::SessionContextMenu,
            "next",
            "down",
            AppEvent::SessionContextNext,
            "Next context-menu item",
        ),
        app(
            Context::SessionContextMenu,
            "next_j",
            "j",
            AppEvent::SessionContextNext,
            "Next context-menu item",
        ),
        app(
            Context::SessionContextMenu,
            "activate",
            "enter",
            AppEvent::SessionContextActivate,
            "Activate context-menu item",
        ),
        app(
            Context::SessionContextMenu,
            "cancel",
            "esc",
            AppEvent::SessionContextCancel,
            "Close context menu",
        ),
        app(
            Context::QuickCommit,
            "confirm",
            "enter",
            AppEvent::QuickCommitConfirm,
            "Commit message",
        ),
        app(
            Context::QuickCommit,
            "cancel",
            "esc",
            AppEvent::QuickCommitCancel,
            "Cancel quick commit",
        ),
        app(
            Context::QuickCommit,
            "backspace",
            "backspace",
            AppEvent::QuickCommitBackspace,
            "Delete previous character",
        ),
        app(
            Context::QuickCommit,
            "cursor_left",
            "left",
            AppEvent::QuickCommitCursorLeft,
            "Move cursor left",
        ),
        app(
            Context::QuickCommit,
            "cursor_right",
            "right",
            AppEvent::QuickCommitCursorRight,
            "Move cursor right",
        ),
        action(
            Context::PreviewScroll,
            "exit",
            "esc",
            KeyAction::Ui(UiAction::PreviewExitScroll),
            "Exit preview scroll mode",
        ),
        action(
            Context::PreviewScroll,
            "up",
            "up",
            KeyAction::Ui(UiAction::PreviewScrollUp),
            "Scroll preview up",
        ),
        action(
            Context::PreviewScroll,
            "up_k",
            "k",
            KeyAction::Ui(UiAction::PreviewScrollUp),
            "Scroll preview up",
        ),
        action(
            Context::PreviewScroll,
            "down",
            "down",
            KeyAction::Ui(UiAction::PreviewScrollDown),
            "Scroll preview down",
        ),
        action(
            Context::PreviewScroll,
            "down_j",
            "j",
            KeyAction::Ui(UiAction::PreviewScrollDown),
            "Scroll preview down",
        ),
        action(
            Context::PreviewScroll,
            "page_up",
            "pageup",
            KeyAction::Ui(UiAction::PreviewPageUp),
            "Scroll preview one page up",
        ),
        action(
            Context::PreviewScroll,
            "page_down",
            "pagedown",
            KeyAction::Ui(UiAction::PreviewPageDown),
            "Scroll preview one page down",
        ),
        app(
            Context::EmbedInteractive,
            "detach",
            "ctrl+q",
            AppEvent::DetachSession,
            "Release interactive embed",
        ),
        action(
            Context::screen("session_list"),
            "attach",
            "enter",
            KeyAction::Ui(UiAction::SessionActivateSelected),
            "Attach selected session",
        ),
        app(
            Context::screen("session_list"),
            "quick_shell",
            "$",
            AppEvent::OpenQuickShell,
            "Open shell in selected workspace",
        ),
        app(
            Context::screen("session_list"),
            "new_session",
            "n",
            AppEvent::NewSession,
            "Create session",
        ),
        app(
            Context::screen("session_list"),
            "cleanup",
            "x",
            AppEvent::CleanupOrphaned,
            "Clean up orphaned sessions",
        ),
        action(
            Context::screen("session_list"),
            "restart",
            "r",
            KeyAction::Ui(UiAction::SessionResumeSelected),
            "Resume selected stopped session",
        ),
        app(
            Context::screen("session_list"),
            "next",
            "down",
            AppEvent::NextSession,
            "Select next session",
        ),
        app(
            Context::screen("session_list"),
            "previous",
            "up",
            AppEvent::PreviousSession,
            "Select previous session",
        ),
        app(
            Context::screen("home"),
            "daemons",
            "d",
            AppEvent::GoToDaemons,
            "Open daemon status",
        ),
        app(
            Context::screen("home"),
            "config",
            "o",
            AppEvent::GoToConfig,
            "Open configuration",
        ),
        app(
            Context::screen("home"),
            "sessions",
            "s",
            AppEvent::GoToSessionList,
            "Open sessions",
        ),
        app(
            Context::screen("home"),
            "stats",
            "i",
            AppEvent::GoToStats,
            "Open usage statistics",
        ),
        app(
            Context::screen("home"),
            "witr",
            "w",
            AppEvent::GoToWitr,
            "Open WITR",
        ),
        app(
            Context::screen("home"),
            "learnings",
            "m",
            AppEvent::GoToLearnings,
            "Open learnings",
        ),
        app(
            Context::screen("home"),
            "abtop",
            "t",
            AppEvent::GoToAbtop,
            "Open ABTOP",
        ),
        app(
            Context::screen("home"),
            "skills",
            "c",
            AppEvent::GoToSkills,
            "Open skills",
        ),
        app(
            Context::screen("home"),
            "setup",
            "u",
            AppEvent::GoToSetupMenu,
            "Open setup",
        ),
        app(
            Context::screen("home"),
            "logs",
            "l",
            AppEvent::GoToLogHistory,
            "Open log history",
        ),
        app(
            Context::screen("home"),
            "skill_manager",
            "z",
            AppEvent::GoToSkillManager,
            "Open skill manager",
        ),
        app(
            Context::screen("home"),
            "hangar",
            "g",
            AppEvent::GoToHangar,
            "Open hangar",
        ),
        app(
            Context::screen("home"),
            "recovery",
            "r",
            AppEvent::GoToRecovery,
            "Open session recovery",
        ),
        app(
            Context::screen("home"),
            "mcp_pool",
            "p",
            AppEvent::McpOverlayOpen,
            "Open MCP pool",
        ),
        app(
            Context::screen("home"),
            "changelog",
            "v",
            AppEvent::ShowChangelog,
            "Show changelog",
        ),
        app(
            Context::screen("home"),
            "new_session",
            "n",
            AppEvent::NewSession,
            "Create session",
        ),
        app(
            Context::screen("home"),
            "toggle_focus",
            "tab",
            AppEvent::HomeScreenToggleFocus,
            "Switch home focus",
        ),
        app(
            Context::screen("daemons"),
            "back",
            "esc",
            AppEvent::PanelBack,
            "Return to previous screen",
        ),
        app(
            Context::screen("daemons"),
            "back_q",
            "q",
            AppEvent::PanelBack,
            "Return to previous screen",
        ),
        app(
            Context::screen("daemons"),
            "refresh",
            "r",
            AppEvent::DaemonsRefresh,
            "Refresh daemon status",
        ),
        app(
            Context::screen("daemons"),
            "repair_hooks",
            "I",
            AppEvent::DaemonsRepairHooks,
            "Repair hooks",
        ),
        app(
            Context::screen("daemons"),
            "pin_hooks",
            "B",
            AppEvent::DaemonsPinHookBinary,
            "Pin hooks to current binary",
        ),
        app(
            Context::Global,
            "help",
            "?",
            AppEvent::ToggleHelp,
            "Toggle keyboard help",
        ),
        app(
            Context::Global,
            "help_h",
            "H",
            AppEvent::ToggleHelp,
            "Toggle keyboard help",
        ),
        app(
            Context::Screen("notifications", super::keymap::SubContext::Named("visible")),
            "dismiss_notifications",
            "ctrl+x",
            AppEvent::DismissNotifications,
            "Dismiss notifications",
        ),
        app(
            Context::Global,
            "go_home",
            "q",
            AppEvent::GoToHomeScreen,
            "Return to home screen",
        ),
        app(
            Context::Global,
            "go_home_escape",
            "esc",
            AppEvent::GoToHomeScreen,
            "Return to home screen",
        ),
        app(
            Context::Global,
            "quit_ctrl",
            "ctrl+c",
            AppEvent::Quit,
            "Quit",
        ),
        action(
            Context::Global,
            "wire_statusline",
            "W",
            KeyAction::Ui(UiAction::UsageWireStatusline),
            "Wire Claude Code statusline when needed",
        ),
        action(
            Context::Global,
            "open_slash_palette",
            ":",
            KeyAction::OpenSlashPalette,
            "Open slash-command palette",
        ),
    ];

    // Printable text is data-owned by `Keymap::resolve_with_context`: it
    // emits `KeyAction::Text` for any bare printable chord after concrete
    // modal and screen rows fail. The 491 defaults below are therefore all
    // named host bindings, never filler copies of the printable alphabet.
    append_app_rows!(rows, Context::OtherTmuxRename,
        confirm: "enter" => AppEvent::OtherTmuxConfirmRename,
        cancel: "esc" => AppEvent::OtherTmuxCancelRename,
        backspace: "backspace" => AppEvent::OtherTmuxRenameBackspace,
    );
    append_app_rows!(rows, Context::SshRename,
        confirm: "enter" => AppEvent::SshSessionConfirmRename,
        cancel: "esc" => AppEvent::SshSessionCancelRename,
        backspace: "backspace" => AppEvent::SshSessionRenameBackspace,
    );
    append_app_rows!(rows, Context::SessionRename,
        confirm: "enter" => AppEvent::SessionLabelConfirmRename,
        cancel: "esc" => AppEvent::SessionLabelCancelRename,
        backspace: "backspace" => AppEvent::SessionLabelRenameBackspace,
    );
    append_app_rows!(rows, Context::Screen("auth_setup", super::keymap::SubContext::Named("picker")),
        show_command: "c" => AppEvent::AuthSetupShowCommand,
    );
    append_app_rows!(rows, Context::Screen("auth_setup", super::keymap::SubContext::Named("input")),
        select: "enter" => AppEvent::AuthSetupSelect,
        backspace: "backspace" => AppEvent::AuthSetupBackspace,
        clear: "esc" => AppEvent::AuthSetupBackspace,
    );
    append_app_rows!(rows, Context::Screen("session_list", super::keymap::SubContext::Named("sessions_pane")),
        top: "home" => AppEvent::GoToTop,
        bottom: "end" => AppEvent::GoToBottom,
    );
    append_app_rows!(rows, Context::Screen("session_list", super::keymap::SubContext::Named("logs_pane")),
        up: "up" => AppEvent::ScrollLogsUp,
        down: "down" => AppEvent::ScrollLogsDown,
        top: "home" => AppEvent::ScrollLogsToTop,
        bottom: "end" => AppEvent::ScrollLogsToBottom,
        toggle_auto_scroll: "space" => AppEvent::ToggleAutoScroll,
    );
    append_app_rows!(rows, Context::Screen("session_list", super::keymap::SubContext::Named("preview_pane")),
        up: "up" => AppEvent::ScrollLogsUp,
        down: "down" => AppEvent::ScrollLogsDown,
        top: "home" => AppEvent::ScrollLogsToTop,
        bottom: "end" => AppEvent::ScrollLogsToBottom,
        toggle_auto_scroll: "space" => AppEvent::ToggleAutoScroll,
    );
    append_app_rows!(rows, Context::screen("search_workspace"),
        cancel: "esc" => AppEvent::NewSessionCancel,
    );
    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("browse_query")),
        backspace: "backspace" => AppEvent::SkillManagerBrowseInputBackspace,
    );
    append_app_rows!(rows, Context::Screen("onboarding", super::keymap::SubContext::Named("dependency_agent")),
        claude: "c" => AppEvent::OnboardingGenerateScript(crate::setup::Agent::Claude),
        claude_upper: "C" => AppEvent::OnboardingGenerateScript(crate::setup::Agent::Claude),
        codex: "x" => AppEvent::OnboardingGenerateScript(crate::setup::Agent::Codex),
        codex_upper: "X" => AppEvent::OnboardingGenerateScript(crate::setup::Agent::Codex),
        antigravity: "a" => AppEvent::OnboardingGenerateScript(crate::setup::Agent::Antigravity),
        antigravity_upper: "A" => AppEvent::OnboardingGenerateScript(crate::setup::Agent::Antigravity),
        copilot: "p" => AppEvent::OnboardingGenerateScript(crate::setup::Agent::Copilot),
        copilot_upper: "P" => AppEvent::OnboardingGenerateScript(crate::setup::Agent::Copilot),
        cancel: "esc" => AppEvent::OnboardingCancelScriptPrompt,
    );
    append_app_rows!(rows, Context::Screen("onboarding", super::keymap::SubContext::Named("auth_key")),
        select: "enter" => AppEvent::OnboardingAuthSelect,
        cancel: "esc" => AppEvent::OnboardingAuthCancel,
        backspace: "backspace" => AppEvent::OnboardingAuthKeyBackspace,
    );
    append_app_rows!(rows, Context::Screen("onboarding", super::keymap::SubContext::Named("auth_method")),
        up: "up" => AppEvent::OnboardingAuthUp,
        down: "down" => AppEvent::OnboardingAuthDown,
        select: "enter" => AppEvent::OnboardingAuthSelect,
        cancel: "esc" => AppEvent::OnboardingAuthCancel,
    );
    append_app_rows!(rows, Context::Screen("onboarding", super::keymap::SubContext::Named("auth_agents")),
        up: "up" => AppEvent::OnboardingAuthUp,
        down: "down" => AppEvent::OnboardingAuthDown,
        select: "enter" => AppEvent::OnboardingAuthSelect,
        next: "right" => AppEvent::OnboardingNext,
        menu: "esc" => AppEvent::OnboardingToMenu,
        back: "left" => AppEvent::OnboardingBack,
        backspace: "backspace" => AppEvent::OnboardingBack,
    );
    append_app_rows!(rows, Context::Screen("onboarding", super::keymap::SubContext::Named("otel")),
        next_field: "tab" => AppEvent::OnboardingOtelNextField,
        previous_field: "shift+tab" => AppEvent::OnboardingOtelPrevField,
        backspace: "backspace" => AppEvent::OnboardingOtelBackspace,
        menu: "esc" => AppEvent::OnboardingToMenu,
    );

    append_app_rows!(rows, Context::screen("skill_manager"),
        back: "q" => AppEvent::SkillManagerBack,
        tab: "tab" => AppEvent::SkillManagerToggleFocus,
        backtab: "shift+tab" => AppEvent::SkillManagerToggleFocus,
        shrink_sources: "[" => AppEvent::SkillManagerShrinkSources,
        grow_sources: "]" => AppEvent::SkillManagerGrowSources,
        add_source: "i" => AppEvent::SkillManagerOpenAddSource,
        update: "u" => AppEvent::SkillManagerUpdate,
        check: "c" => AppEvent::SkillManagerCheck,
        browse: "b" => AppEvent::SkillManagerOpenBrowse,
        library: "l" => AppEvent::SkillManagerOpenLibrary,
        search: "/" => AppEvent::SkillManagerOpenSearch,
        discovery: "m" => AppEvent::SkillManagerRefreshDiscovery,
        select_prev: "up" => AppEvent::SkillManagerSelectPrev,
        select_prev_k: "k" => AppEvent::SkillManagerSelectPrev,
        select_next: "down" => AppEvent::SkillManagerSelectNext,
        select_next_j: "j" => AppEvent::SkillManagerSelectNext,
        select_first: "home" => AppEvent::SkillManagerSelectFirst,
        select_first_g: "g" => AppEvent::SkillManagerSelectFirst,
        select_last: "end" => AppEvent::SkillManagerSelectLast,
        select_last_g: "G" => AppEvent::SkillManagerSelectLast,
    );
    append_action_rows!(rows, Context::screen("skill_manager"),
        sync_or_conflict: "s" => KeyAction::Ui(UiAction::SkillManagerSyncOrConflict),
        remove_or_source: "r" => KeyAction::Ui(UiAction::SkillManagerRemoveOrSource),
        open_unit: "o" => KeyAction::Ui(UiAction::SkillManagerOpenUnitIfFocused),
        copy_unit: "y" => KeyAction::Ui(UiAction::SkillManagerCopyToLibraryIfFocused),
        back_or_clear_filter: "esc" => KeyAction::Ui(UiAction::SkillManagerBackOrClearFilter),
    );

    append_app_rows!(rows, Context::HelpVisible,
        close_escape: "esc" => AppEvent::ToggleHelp,
        close_help: "?" => AppEvent::ToggleHelp,
        close_help_upper: "H" => AppEvent::ToggleHelp,
    );
    append_app_rows!(rows, Context::Screen("help", super::keymap::SubContext::Named("text")),
        close_escape: "esc" => AppEvent::ToggleHelp,
    );
    append_app_rows!(rows, Context::Screen("plugin", super::keymap::SubContext::Named("owned")),
        back: "esc" => AppEvent::PanelBack,
        back_q: "q" => AppEvent::PanelBack,
    );

    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("sync_confirm")),
        previous: "up" => AppEvent::SkillManagerSyncScroll(-1),
        previous_k: "k" => AppEvent::SkillManagerSyncScroll(-1),
        next: "down" => AppEvent::SkillManagerSyncScroll(1),
        next_j: "j" => AppEvent::SkillManagerSyncScroll(1),
        confirm: "enter" => AppEvent::SkillManagerSyncConfirm,
        cancel: "esc" => AppEvent::SkillManagerSyncCancel,
        cancel_q: "q" => AppEvent::SkillManagerSyncCancel,
    );

    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("preview")),
        previous: "up" => AppEvent::SkillManagerPreviewUp,
        previous_k: "k" => AppEvent::SkillManagerPreviewUp,
        next: "down" => AppEvent::SkillManagerPreviewDown,
        next_j: "j" => AppEvent::SkillManagerPreviewDown,
        toggle: "space" => AppEvent::SkillManagerPreviewToggle,
        all: "a" => AppEvent::SkillManagerPreviewAll,
        none: "n" => AppEvent::SkillManagerPreviewNone,
        tool_one: "1" => AppEvent::SkillManagerPreviewTool(0),
        tool_two: "2" => AppEvent::SkillManagerPreviewTool(1),
        tool_three: "3" => AppEvent::SkillManagerPreviewTool(2),
        tool_four: "4" => AppEvent::SkillManagerPreviewTool(3),
        confirm: "enter" => AppEvent::SkillManagerPreviewConfirm,
        close: "esc" => AppEvent::SkillManagerPreviewClose,
        close_q: "q" => AppEvent::SkillManagerPreviewClose,
    );

    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("source_remove")),
        previous: "up" => AppEvent::SkillManagerSourceRemoveMove(-1),
        previous_k: "k" => AppEvent::SkillManagerSourceRemoveMove(-1),
        next: "down" => AppEvent::SkillManagerSourceRemoveMove(1),
        next_j: "j" => AppEvent::SkillManagerSourceRemoveMove(1),
        confirm: "enter" => AppEvent::SkillManagerSourceRemoveConfirm,
        cancel: "esc" => AppEvent::SkillManagerSourceRemoveCancel,
        cancel_q: "q" => AppEvent::SkillManagerSourceRemoveCancel,
    );

    append_app_rows!(rows, Context::screen("git_view"),
        back: "esc" => AppEvent::GitViewBack,
        switch_tab: "tab" => AppEvent::GitViewSwitchTab,
        start_commit: "p" => AppEvent::GitViewStartCommit,
    );
    append_app_rows!(rows, Context::Screen("git_view", super::keymap::SubContext::Named("review")),
        next_hunk: "n" => AppEvent::GitReviewNextHunk,
        previous_hunk: "N" => AppEvent::GitReviewPrevHunk,
        next_file: "]" => AppEvent::GitReviewNextReviewFile,
        previous_file: "[" => AppEvent::GitReviewPrevReviewFile,
        toggle: "space" => AppEvent::GitReviewToggleCollapse,
        toggle_enter: "enter" => AppEvent::GitReviewToggleCollapse,
        context: "z" => AppEvent::GitReviewExpandContext,
        expand: "e" => AppEvent::GitReviewExpandAllFolders,
        collapse: "E" => AppEvent::GitReviewCollapseAllFolders,
        scroll_down: "j" => AppEvent::GitViewScrollDown,
        scroll_down_arrow: "down" => AppEvent::GitViewScrollDown,
        scroll_up: "k" => AppEvent::GitViewScrollUp,
        scroll_up_arrow: "up" => AppEvent::GitViewScrollUp,
    );

    append_app_rows!(rows, Context::screen("log_history"),
        back: "esc" => AppEvent::LogHistoryBack,
        cycle_filter: "f" => AppEvent::LogHistoryCycleFilter,
        refresh: "r" => AppEvent::LogHistoryRefresh,
        copy: "y" => AppEvent::LogHistoryCopySelection,
        cleanup: "c" => AppEvent::LogHistoryCleanup,
        cleanup_upper: "C" => AppEvent::LogHistoryCleanup,
        toggle_focus: "tab" => AppEvent::LogHistoryToggleFocus,
        home: "home" => AppEvent::LogHistoryScrollHome,
    );
    append_app_rows!(rows, Context::Screen("log_history", super::keymap::SubContext::Named("sessions")),
        previous: "up" => AppEvent::LogHistoryPrevSession,
        previous_k: "k" => AppEvent::LogHistoryPrevSession,
        next: "down" => AppEvent::LogHistoryNextSession,
        next_j: "j" => AppEvent::LogHistoryNextSession,
        select: "enter" => AppEvent::LogHistorySelectSession,
    );
    append_app_rows!(rows, Context::Screen("log_history", super::keymap::SubContext::Named("logs")),
        up: "up" => AppEvent::LogHistoryScrollUp,
        up_k: "k" => AppEvent::LogHistoryScrollUp,
        down: "down" => AppEvent::LogHistoryScrollDown,
        down_j: "j" => AppEvent::LogHistoryScrollDown,
        page_up: "pageup" => AppEvent::LogHistoryPageUp,
        page_down: "pagedown" => AppEvent::LogHistoryPageDown,
        left: "left" => AppEvent::LogHistoryScrollLeft,
        left_h: "h" => AppEvent::LogHistoryScrollLeft,
        right: "right" => AppEvent::LogHistoryScrollRight,
        right_l: "l" => AppEvent::LogHistoryScrollRight,
    );

    append_app_rows!(rows, Context::screen("skills"),
        back: "esc" => AppEvent::SkillsBack,
        next_provider: "right" => AppEvent::SkillsNextProvider,
        next_provider_l: "l" => AppEvent::SkillsNextProvider,
        previous_provider: "left" => AppEvent::SkillsPrevProvider,
        previous_provider_h: "h" => AppEvent::SkillsPrevProvider,
        next_tab: "tab" => AppEvent::SkillsNextTab,
        previous_tab: "shift+tab" => AppEvent::SkillsPrevTab,
        scroll_up: "up" => AppEvent::SkillsScrollUp,
        scroll_up_k: "k" => AppEvent::SkillsScrollUp,
        scroll_down: "down" => AppEvent::SkillsScrollDown,
        scroll_down_j: "j" => AppEvent::SkillsScrollDown,
        page_up: "pageup" => AppEvent::SkillsPageUp,
        page_down: "pagedown" => AppEvent::SkillsPageDown,
        top: "g" => AppEvent::SkillsToTop,
        bottom: "G" => AppEvent::SkillsToBottom,
        refresh: "r" => AppEvent::SkillsRefresh,
        search: "/" => AppEvent::SkillsSearchStart,
    );

    append_app_rows!(rows, Context::screen("changelog"),
        back: "esc" => AppEvent::ChangelogBack,
        up: "up" => AppEvent::ChangelogScrollUp,
        up_k: "k" => AppEvent::ChangelogScrollUp,
        down: "down" => AppEvent::ChangelogScrollDown,
        down_j: "j" => AppEvent::ChangelogScrollDown,
        page_up: "pageup" => AppEvent::ChangelogPageUp,
        page_down: "pagedown" => AppEvent::ChangelogPageDown,
        top: "g" => AppEvent::ChangelogToTop,
        bottom: "G" => AppEvent::ChangelogToBottom,
    );

    append_app_rows!(rows, Context::screen("session_recovery"),
        back: "esc" => AppEvent::SessionRecoveryBack,
        previous: "up" => AppEvent::SessionRecoveryPrev,
        previous_k: "k" => AppEvent::SessionRecoveryPrev,
        next: "down" => AppEvent::SessionRecoveryNext,
        next_j: "j" => AppEvent::SessionRecoveryNext,
        resume: "r" => AppEvent::SessionRecoveryResume,
        archive: "d" => AppEvent::SessionRecoveryArchive,
        refresh: "R" => AppEvent::SessionRecoveryRefresh,
        toggle_view: "tab" => AppEvent::SessionRecoveryToggleView,
        recover_all: "A" => AppEvent::SessionRecoveryRecoverAll,
        toggle: "space" => AppEvent::SessionRecoveryToggleSelect,
        delete: "D" => AppEvent::SessionRecoveryDeleteSelected,
        search: "/" => AppEvent::SessionRecoverySearchStart,
    );

    append_app_rows!(rows, Context::screen("config"),
        back: "esc" => AppEvent::ConfigBack,
        switch_pane: "tab" => AppEvent::ConfigSwitchPane,
        search: "/" => AppEvent::ConfigSearchStart,
        secret: "ctrl+k" => AppEvent::ConfigSecretToKeychain,
        up: "up" => AppEvent::ConfigNavigateUp,
        up_k: "k" => AppEvent::ConfigNavigateUp,
        down: "down" => AppEvent::ConfigNavigateDown,
        down_j: "j" => AppEvent::ConfigNavigateDown,
        left: "left" => AppEvent::ConfigFocusCategories,
        left_h: "h" => AppEvent::ConfigFocusCategories,
        right: "right" => AppEvent::ConfigFocusSettings,
        right_l: "l" => AppEvent::ConfigFocusSettings,
        toggle_expand: "space" => AppEvent::ConfigToggleExpand,
        save_all: "s" => AppEvent::ConfigSaveAll,
        save_all_upper: "S" => AppEvent::ConfigSaveAll,
    );

    append_app_rows!(rows, Context::AuthProviderPopup,
        close: "esc" => AppEvent::AuthProviderPopupClose,
        previous: "up" => AppEvent::AuthProviderPopupPrev,
        previous_k: "k" => AppEvent::AuthProviderPopupPrev,
        next: "down" => AppEvent::AuthProviderPopupNext,
        next_j: "j" => AppEvent::AuthProviderPopupNext,
        select: "enter" => AppEvent::AuthProviderPopupSelect,
        delete: "d" => AppEvent::AuthProviderPopupDeleteKey,
        delete_upper: "D" => AppEvent::AuthProviderPopupDeleteKey,
    );

    append_app_rows!(rows, Context::ConfigPopup,
        cancel: "esc" => AppEvent::ConfigPopupCancel,
        up: "up" => AppEvent::ConfigPopupNavigateUp,
        up_k: "k" => AppEvent::ConfigPopupNavigateUp,
        down: "down" => AppEvent::ConfigPopupNavigateDown,
        down_j: "j" => AppEvent::ConfigPopupNavigateDown,
        confirm: "enter" => AppEvent::ConfigPopupConfirm,
        backspace: "backspace" => AppEvent::ConfigPopupBackspace,
        delete: "delete" => AppEvent::ConfigPopupDelete,
        left: "left" => AppEvent::ConfigPopupCursorLeft,
        right: "right" => AppEvent::ConfigPopupCursorRight,
        home: "home" => AppEvent::ConfigPopupCursorHome,
        end: "end" => AppEvent::ConfigPopupCursorEnd,
        paste: "ctrl+v" => AppEvent::ConfigPopupPasteClipboard,
    );

    append_app_rows!(rows, Context::screen("session_list"),
        back: "esc" => AppEvent::GoToHomeScreen,
        back_q: "q" => AppEvent::GoToHomeScreen,
        tab_next: "tab" => AppEvent::SessionTabNext,
        tab_previous: "shift+tab" => AppEvent::SessionTabPrev,
        toggle_chat: "c" => AppEvent::ToggleClaudeChat,
        refresh: "f" => AppEvent::RefreshWorkspaces,
        cycle_filter: "F" => AppEvent::CycleSessionFilter,
        star: "s" => AppEvent::StarSelectedWorkspace,
        star_upper: "S" => AppEvent::StarSelectedWorkspace,
        attach_tmux: "a" => AppEvent::AttachTmuxSession,
        attach_interactive: "A" => AppEvent::EnterInteractivePane,
        reauthenticate: "u" => AppEvent::ReauthenticateCredentials,
        restart: "e" => AppEvent::RestartSession,
        toggle_selected: "space" => AppEvent::ToggleSelectSession,
        delete_selected: "D" => AppEvent::DeleteSelectedSessions,
        delete: "d" => AppEvent::DeleteSession,
        cleanup_ctrl: "ctrl+x" => AppEvent::CleanupOrphaned,
        git: "g" => AppEvent::ShowGitView,
        quick_commit: "p" => AppEvent::QuickCommitStart,
        editor: "o" => AppEvent::OpenInEditor,
        expand: "E" => AppEvent::ToggleExpandAll,
        sidebar: "B" => AppEvent::ToggleSessionsSidebar,
        menu_bar: "M" => AppEvent::ToggleSessionMenuBar,
        stats: "i" => AppEvent::GoToStats,
        witr: "w" => AppEvent::GoToWitr,
        skills: "k" => AppEvent::GoToSkills,
        learnings: "m" => AppEvent::GoToLearnings,
        abtop: "t" => AppEvent::GoToAbtop,
        preview_up: "shift+up" => AppEvent::ScrollPreviewUp,
        preview_down: "shift+down" => AppEvent::ScrollPreviewDown,
    );
    append_action_rows!(rows, Context::screen("session_list"),
        rename: "f2" => KeyAction::Ui(UiAction::SessionStartRename),
        headroom_or_help: "H" => KeyAction::Ui(UiAction::SessionHeadroomOrHelp),
        attach_one: "1" => KeyAction::Ui(UiAction::AttachSessionByPosition(1)),
        attach_two: "2" => KeyAction::Ui(UiAction::AttachSessionByPosition(2)),
        attach_three: "3" => KeyAction::Ui(UiAction::AttachSessionByPosition(3)),
        attach_four: "4" => KeyAction::Ui(UiAction::AttachSessionByPosition(4)),
        attach_five: "5" => KeyAction::Ui(UiAction::AttachSessionByPosition(5)),
        attach_six: "6" => KeyAction::Ui(UiAction::AttachSessionByPosition(6)),
        attach_seven: "7" => KeyAction::Ui(UiAction::AttachSessionByPosition(7)),
        attach_eight: "8" => KeyAction::Ui(UiAction::AttachSessionByPosition(8)),
        attach_nine: "9" => KeyAction::Ui(UiAction::AttachSessionByPosition(9)),
    );

    append_app_rows!(rows, Context::Screen("home", super::keymap::SubContext::Named("sidebar")),
        up: "up" => AppEvent::HomeScreenSidebarUp,
        down: "down" => AppEvent::HomeScreenSidebarDown,
        select: "enter" => AppEvent::HomeScreenSidebarSelect,
    );
    append_app_rows!(rows, Context::Screen("home", super::keymap::SubContext::Named("content")),
        up: "up" => AppEvent::WelcomePanelScrollUp,
        down: "down" => AppEvent::WelcomePanelScrollDown,
        page_up: "pageup" => AppEvent::WelcomePanelPageUp,
        page_down: "pagedown" => AppEvent::WelcomePanelPageDown,
        copy: "y" => AppEvent::WelcomePanelCopyContent,
    );

    append_app_rows!(rows, Context::Screen("config", super::keymap::SubContext::Named("editing")),
        save: "enter" => AppEvent::ConfigSaveEdit,
        cancel: "esc" => AppEvent::ConfigCancelEdit,
        backspace: "backspace" => AppEvent::ConfigEditBackspace,
    );
    append_app_rows!(rows, Context::Screen("config", super::keymap::SubContext::Named("api_key")),
        save: "enter" => AppEvent::ConfigApiKeySave,
        cancel: "esc" => AppEvent::ConfigCancelEdit,
        backspace: "backspace" => AppEvent::ConfigEditBackspace,
    );
    append_app_rows!(rows, Context::Screen("config", super::keymap::SubContext::Named("search")),
        cancel: "esc" => AppEvent::ConfigSearchCancel,
        previous: "up" => AppEvent::ConfigPrevSetting,
        next: "down" => AppEvent::ConfigNextSetting,
        edit: "enter" => AppEvent::ConfigEditSetting,
        backspace: "backspace" => AppEvent::ConfigSearchBackspace,
        secret: "ctrl+k" => AppEvent::ConfigSecretToKeychain,
    );
    append_app_rows!(rows, Context::Screen("auth_provider_popup", super::keymap::SubContext::Named("input")),
        select: "enter" => AppEvent::AuthProviderPopupSelect,
        close: "esc" => AppEvent::AuthProviderPopupClose,
        backspace: "backspace" => AppEvent::AuthProviderPopupBackspace,
    );

    append_app_rows!(rows, Context::Screen("skills", super::keymap::SubContext::Named("search")),
        close: "esc" => AppEvent::SkillsSearchClose,
        close_enter: "enter" => AppEvent::SkillsSearchClose,
        backspace: "backspace" => AppEvent::SkillsSearchBackspace,
    );
    append_app_rows!(rows, Context::Screen("session_recovery", super::keymap::SubContext::Named("search")),
        cancel: "esc" => AppEvent::SessionRecoverySearchCancel,
        close: "enter" => AppEvent::SessionRecoverySearchClose,
        backspace: "backspace" => AppEvent::SessionRecoverySearchBackspace,
        previous: "up" => AppEvent::SessionRecoveryPrev,
        next: "down" => AppEvent::SessionRecoveryNext,
    );
    append_app_rows!(rows, Context::Screen("git_view", super::keymap::SubContext::Named("commit")),
        cancel: "esc" => AppEvent::GitViewCommitCancel,
        confirm: "enter" => AppEvent::GitViewCommitConfirm,
        backspace: "backspace" => AppEvent::GitViewCommitBackspace,
        left: "left" => AppEvent::GitViewCommitCursorLeft,
        right: "right" => AppEvent::GitViewCommitCursorRight,
    );

    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("input")),
        submit: "enter" => AppEvent::SkillManagerInputSubmit,
        cancel: "esc" => AppEvent::SkillManagerInputCancel,
        backspace: "backspace" => AppEvent::SkillManagerInputBackspace,
    );
    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("browse_query")),
        catalog: "tab" => AppEvent::SkillManagerBrowseToggleCatalog,
        catalog_back: "shift+tab" => AppEvent::SkillManagerBrowseToggleCatalog,
        search: "enter" => AppEvent::SkillManagerBrowseSearch,
        close: "esc" => AppEvent::SkillManagerBrowseClose,
    );
    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("browse_results")),
        previous: "up" => AppEvent::SkillManagerBrowseSelectPrev,
        previous_k: "k" => AppEvent::SkillManagerBrowseSelectPrev,
        next: "down" => AppEvent::SkillManagerBrowseSelectNext,
        next_j: "j" => AppEvent::SkillManagerBrowseSelectNext,
        catalog: "tab" => AppEvent::SkillManagerBrowseToggleCatalog,
        install: "enter" => AppEvent::SkillManagerBrowseInstall,
        query: "/" => AppEvent::SkillManagerBrowseEditQuery,
    );
    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("library")),
        previous: "up" => AppEvent::SkillManagerLibrarySelectPrev,
        previous_k: "k" => AppEvent::SkillManagerLibrarySelectPrev,
        next: "down" => AppEvent::SkillManagerLibrarySelectNext,
        next_j: "j" => AppEvent::SkillManagerLibrarySelectNext,
        enter: "enter" => AppEvent::SkillManagerLibraryEnter,
        close: "esc" => AppEvent::SkillManagerLibraryClose,
    );
    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("discovery")),
        import: "enter" => AppEvent::SkillManagerDiscoveryImport,
        details: "d" => AppEvent::SkillManagerDiscoveryToggleDetails,
        skip: "s" => AppEvent::SkillManagerDiscoverySkip,
        back: "esc" => AppEvent::SkillManagerBack,
    );
    append_app_rows!(rows, Context::Screen("skill_manager", super::keymap::SubContext::Named("sources")),
        previous: "up" => AppEvent::SkillManagerSourceSelectPrev,
        previous_k: "k" => AppEvent::SkillManagerSourceSelectPrev,
        next: "down" => AppEvent::SkillManagerSourceSelectNext,
        next_j: "j" => AppEvent::SkillManagerSourceSelectNext,
        preview: "enter" => AppEvent::SkillManagerPreviewSource,
        filter: "f" => AppEvent::SkillManagerApplySourceFilterKey,
    );

    append_app_rows!(rows, Context::Screen("auth_setup", super::keymap::SubContext::Named("picker")),
        cancel: "esc" => AppEvent::AuthSetupCancel,
        previous: "up" => AppEvent::AuthSetupPrevious,
        previous_k: "k" => AppEvent::AuthSetupPrevious,
        next: "down" => AppEvent::AuthSetupNext,
        next_j: "j" => AppEvent::AuthSetupNext,
        select: "enter" => AppEvent::AuthSetupSelect,
        refresh: "r" => AppEvent::AuthSetupRefresh,
    );

    append_app_rows!(rows, Context::Screen("onboarding", super::keymap::SubContext::Named("git_directories")),
        next: "enter" => AppEvent::OnboardingNext,
        menu: "esc" => AppEvent::OnboardingToMenu,
        back: "up" => AppEvent::OnboardingBack,
        backspace: "backspace" => AppEvent::OnboardingBackspace,
        delete: "delete" => AppEvent::OnboardingDelete,
        left: "left" => AppEvent::OnboardingCursorLeft,
        right: "right" => AppEvent::OnboardingCursorRight,
        home: "home" => AppEvent::OnboardingCursorHome,
        end: "end" => AppEvent::OnboardingCursorEnd,
    );
    append_app_rows!(rows, Context::Screen("onboarding", super::keymap::SubContext::Named("questions")),
        next: "enter" => AppEvent::OnboardingNext,
        next_right: "right" => AppEvent::OnboardingNext,
        menu: "esc" => AppEvent::OnboardingToMenu,
        back: "left" => AppEvent::OnboardingBack,
        backspace: "backspace" => AppEvent::OnboardingBack,
        previous: "up" => AppEvent::OnboardingQuestionUp,
        previous_k: "k" => AppEvent::OnboardingQuestionUp,
        next_question: "down" => AppEvent::OnboardingQuestionDown,
        next_question_j: "j" => AppEvent::OnboardingQuestionDown,
    );
    append_app_rows!(rows, Context::Screen("onboarding", super::keymap::SubContext::Named("dependency")),
        enter: "enter" => AppEvent::OnboardingCheckDeps,
        back: "esc" => AppEvent::OnboardingBack,
        up: "up" => AppEvent::OnboardingDepCursorUp,
        left: "left" => AppEvent::OnboardingDepCursorUp,
        down: "down" => AppEvent::OnboardingDepCursorDown,
        right: "right" => AppEvent::OnboardingDepCursorDown,
        check: "r" => AppEvent::OnboardingCheckDeps,
        install: "i" => AppEvent::OnboardingInstallFocusedDep,
        install_config: "t" => AppEvent::OnboardingInstallConfig,
        script: "g" => AppEvent::OnboardingScriptPrompt,
        script_upper: "G" => AppEvent::OnboardingScriptPrompt,
        install_upper: "I" => AppEvent::OnboardingInstallFocusedDep,
        config_upper: "T" => AppEvent::OnboardingInstallConfig,
    );

    append_app_rows!(rows, Context::Screen("setup_menu", super::keymap::SubContext::Named("menu")),
        back: "esc" => AppEvent::SetupMenuBack,
        previous: "up" => AppEvent::SetupMenuUp,
        previous_k: "k" => AppEvent::SetupMenuUp,
        next: "down" => AppEvent::SetupMenuDown,
        next_j: "j" => AppEvent::SetupMenuDown,
        select: "enter" => AppEvent::SetupMenuSelect,
    );
    append_app_rows!(rows, Context::Screen("setup_menu", super::keymap::SubContext::Named("confirm")),
        yes: "y" => AppEvent::SetupMenuSelect,
        yes_upper: "Y" => AppEvent::SetupMenuSelect,
        confirm: "enter" => AppEvent::SetupMenuSelect,
    );

    append_app_rows!(rows, Context::screen("attached_terminal"),
        detach: "d" => AppEvent::DetachSession,
        detach_q: "q" => AppEvent::DetachSession,
        kill: "k" => AppEvent::KillContainer,
    );
    append_app_rows!(rows, Context::screen("non_git_notification"),
        home: "q" => AppEvent::GoToHomeScreen,
        home_escape: "esc" => AppEvent::GoToHomeScreen,
    );
    append_app_rows!(rows, Context::screen("claude_chat"),
        close: "esc" => AppEvent::ToggleClaudeChat,
    );

    append_action_rows!(rows, Context::Screen("daemons", super::keymap::SubContext::Named("overlay")),
        close: "esc" => KeyAction::Ui(UiAction::DaemonsCloseOverlay),
        close_q: "q" => KeyAction::Ui(UiAction::DaemonsCloseAndBack),
        confirm: "enter" => KeyAction::Ui(UiAction::DaemonsConfirmMenu),
        previous: "up" => KeyAction::Ui(UiAction::DaemonsMoveOverlay(-1)),
        previous_k: "k" => KeyAction::Ui(UiAction::DaemonsMoveOverlay(-1)),
        next: "down" => KeyAction::Ui(UiAction::DaemonsMoveOverlay(1)),
        next_j: "j" => KeyAction::Ui(UiAction::DaemonsMoveOverlay(1)),
    );
    append_action_rows!(rows, Context::Screen("daemons", super::keymap::SubContext::Named("list")),
        open: "enter" => KeyAction::Ui(UiAction::DaemonsOpenMenu),
        previous: "up" => KeyAction::Ui(UiAction::DaemonsMoveSelection(-1)),
        previous_k: "k" => KeyAction::Ui(UiAction::DaemonsMoveSelection(-1)),
        next: "down" => KeyAction::Ui(UiAction::DaemonsMoveSelection(1)),
        next_j: "j" => KeyAction::Ui(UiAction::DaemonsMoveSelection(1)),
    );
    append_app_rows!(rows, Context::Screen("session_list", super::keymap::SubContext::Named("sessions_pane")),
        next: "down" => AppEvent::NextSession,
        previous: "up" => AppEvent::PreviousSession,
        interactive: "right" => AppEvent::EnterInteractivePane,
    );
    append_action_rows!(rows, Context::Screen("session_list", super::keymap::SubContext::Named("composer")),
        enter: "enter" => KeyAction::Ui(UiAction::SessionComposerEnter),
        backspace: "backspace" => KeyAction::Ui(UiAction::SessionComposerBackspace),
        escape: "esc" => KeyAction::Ui(UiAction::SessionComposerEscape),
        up: "up" => KeyAction::Ui(UiAction::SessionComposerUp),
        down: "down" => KeyAction::Ui(UiAction::SessionComposerDown),
        focus_toggle: "shift+tab" => KeyAction::Ui(UiAction::SessionComposerFocusToggle),
        retry: "alt+p" => KeyAction::Ui(UiAction::SessionComposerRetry),
        cancel: "alt+c" => KeyAction::Ui(UiAction::SessionComposerCancel),
        engine: "alt+e" => KeyAction::Ui(UiAction::PalCycleEngine),
        model: "alt+o" => KeyAction::Ui(UiAction::PalCycleModel),
        mode: "alt+g" => KeyAction::Ui(UiAction::PalCycleMode),
        dial_retry: "alt+r" => KeyAction::Ui(UiAction::PalRetry),
    );
    append_action_rows!(rows, Context::Screen("session_list", super::keymap::SubContext::Named("ask")),
        enter: "enter" => KeyAction::App(AppEvent::SessionAskSend),
        previous: "up" => KeyAction::Ui(UiAction::SessionAskPrevious),
        next: "down" => KeyAction::Ui(UiAction::SessionAskNext),
        backspace: "backspace" => KeyAction::Ui(UiAction::SessionAskBackspace),
    );
    append_app_rows!(rows, Context::Screen("session_recovery", super::keymap::SubContext::Named("filtered")),
        clear: "esc" => AppEvent::SessionRecoverySearchCancel,
    );

    rows
}
