// Generated by `cargo test -p ainb-desktop --features typescript-bindings --test bindings`
// from the Rust types the webview sends and receives. Do not edit.
// This file has been generated by Specta. Do not edit this file manually.
/**  One row the palette offers: a command the webview may send by name. */
export type PaletteEntry = {
	id: string,
	/**  What the row does, as the keymap documents it. */
	doc: string,
	/**  The context the row belongs to, for the palette to group by. */
	context: string,
	/**  The key that runs it, when it has one. */
	chord: string | null,
	/**
	 *  Whether the reducer would run it in the state as it stands. A row that
	 *  is not active is still offered, greyed, rather than vanishing as the
	 *  user moves around.
	 */
	active: boolean,
};

/**
 *  The intents a DOM renderer sends: a key, a named command, pasted text.
 * 
 *  A subset of [`Intent`] with the same wire spelling. There is no `Mouse`:
 *  the webview hit-tests its own DOM and sends the command a press means, so a
 *  terminal cell position has nothing to hit here.
 */
export type RendererIntent = ({ Key: string }) & { Command?: never; Text?: never } | ({ Command: [string, unknown] }) & { Key?: never; Text?: never } | ({ Text: string }) & { Command?: never; Key?: never };
