#!/usr/bin/env bash
# ABOUTME: Record one full-length vhs tape per chat-bus smoke journey, plus one
# tape of the whole suite end to end.
#
#   ./record-chat-bus.sh             # every tape (9 journeys + the full run)
#   ./record-chat-bus.sh j2 j5b      # a subset
#   ./record-chat-bus.sh full        # only the whole-suite tape
#
# Each tape runs the REAL harness (`ainb-tui/scripts/chat-bus-smoke.sh`) from
# the command line to the final SMOKE-RESULT line with NO cuts: the recording
# ends when the summary appears on screen (`Wait+Screen`), not after a guessed
# `Sleep`. Nothing is staged, replayed or re-typed for the camera.
#
# The binaries are NOT built inside the tape (that would be minutes of cargo
# noise on every recording). Build once, then point the tapes at the result:
#
#   cd ainb-tui && cargo build -j2 -p ainb -p ainb-hangar-daemon -p ainb-acp --bins
#   AINB_SMOKE_BIN_SOURCE=$PWD/target/debug ../explainers/recordings/chat-bus/record-chat-bus.sh
#
# Knobs:
#   AINB_SMOKE_BIN_SOURCE=<dir>  where the three binaries come from
#                                (default: ainb-tui/target/debug)
#   VHS_NO_SANDBOX=true          set automatically; headless chromium refuses to
#                                start as root/in a container without it
set -Eeuo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd -- "$HERE/../../.." && pwd)"
TUI="$REPO/ainb-tui"
BIN_SOURCE="${AINB_SMOKE_BIN_SOURCE:-$TUI/target/debug}"
export VHS_NO_SANDBOX=true

for tool in vhs ffmpeg tmux jq python3 sqlite3; do
  command -v "$tool" >/dev/null || { echo "missing required tool: $tool" >&2; exit 2; }
done
for bin in ainb ainb-hangar-daemon fake_acp_adapter; do
  [[ -x "$BIN_SOURCE/$bin" ]] || { echo "missing build artifact: $BIN_SOURCE/$bin" >&2; exit 2; }
done

# The generated tape MUST match what PR #640 fixed by hand, or the next run of
# this script silently undoes it. Three rules, each learned by losing a tape:
#   * Output paths are REPO-RELATIVE. An absolute path pins the tape to one
#     machine's checkout and it fails everywhere else.
#   * NO `Set Framerate`. Lowering it does not slow the capture, it blurs it:
#     one attempt rendered a three minute run as 196 frames of 7 seconds.
#   * Terminate on THIS journey's verdict, not `SMOKE-RESULT overall`. A tape
#     recording several journeys would otherwise stop at the first summary.
#
# 1400x800 at 15px is ~151 columns: wider than the harness's longest assertion
# line (J4's `converged UNKNOWN/adapter_exit; …`), so nothing an assertion says
# gets wrapped into noise. 10 fps keeps the GIF small enough to live in the repo
# while still showing the output arriving line by line.
render() { # id journey-args... -> writes <id>.tape, <id>.gif, <id>.mp4, <id>.png
  local id="$1" timeout="$2"; shift 2
  local tape="$HERE/$id.tape"
  {
    printf '# %s.tape — chat-bus live smoke, journey(s): %s\n' "$id" "$*"
    printf '# Generated by record-chat-bus.sh. Full run, no cuts: the tape ends\n'
    printf '# when SMOKE-RESULT appears on screen, not on a guessed Sleep.\n\n'
    printf 'Output explainers/recordings/chat-bus/%s.gif\n' "$id"
    printf 'Output explainers/recordings/chat-bus/%s.mp4\n\n' "$id"
    printf 'Set Shell bash\n'
    printf 'Set Theme "Dracula"\n'
    printf 'Set FontSize 15\n'
    printf 'Set Width 1400\n'
    printf 'Set Height 800\n'
    printf 'Set Padding 20\n'
    printf 'Set TypingSpeed 45ms\n\n'
    printf '# Off camera: cd + the two knobs that keep cargo out of the recording.\n'
    printf 'Hide\n'
    printf 'Type "cd %s"\n' "$REPO"
    printf 'Enter\n'
    printf 'Type "export AINB_SMOKE_SKIP_BUILD=1 AINB_SMOKE_BIN_SOURCE=%s"\n' "$BIN_SOURCE"
    printf 'Enter\n'
    printf 'Type "clear"\n'
    printf 'Enter\n'
    printf 'Show\n'
    printf 'Sleep 1s\n\n'
    printf 'Type "./ainb-tui/scripts/chat-bus-smoke.sh %s"\n' "$*"
    printf 'Enter\n'
    printf 'Wait+Screen@%s /SMOKE-RESULT %s /\n' "$timeout" "$id"
    printf 'Sleep 4s\n'
  } >"$tape"

  echo "== recording $id ($*)"
  # vhs drives a headless chromium. On a loaded box that browser is the first
  # thing an OOM killer takes (`failed to type key: EOF`), which costs a tape,
  # not a journey — so retry rather than lose the recording.
  local attempt
  rm -f "$HERE/$id.gif" "$HERE/$id.mp4"
  for attempt in 1 2 3; do
    vhs "$tape" && [[ -s "$HERE/$id.gif" && -s "$HERE/$id.mp4" ]] && break
    echo "  retry $id (attempt $attempt produced no usable recording)"
    rm -f "$HERE/$id.gif" "$HERE/$id.mp4"
    sleep 10
  done
  [[ -s "$HERE/$id.gif" && -s "$HERE/$id.mp4" ]] || { echo "  FAIL $id (no output)"; return 1; }
  # Poster frame = the last frame = the summary. `Screenshot` in a tape is a
  # no-op on this vhs build, so take it from the video instead.
  ffmpeg -nostdin -loglevel error -y -sseof -1 -i "$HERE/$id.mp4" \
    -update 1 -frames:v 1 "$HERE/$id.png"
  printf '  OK  %s · %ss · gif %s · mp4 %s\n' "$id" \
    "$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$HERE/$id.mp4" | cut -d. -f1)" \
    "$(du -h "$HERE/$id.gif" | cut -f1)" "$(du -h "$HERE/$id.mp4" | cut -f1)"
}

declare -A TIMEOUT=(
  [j1]=600s [j2]=600s [j3]=900s [j4]=600s [j5a]=900s
  [j5b]=900s [j5c]=600s [j5d]=600s [j5e]=600s [full]=2400s
)

record_one() {
  case "$1" in
    full) render full "${TIMEOUT[full]}" all ;;
    j1|j2|j3|j4|j5a|j5b|j5c|j5d|j5e) render "$1" "${TIMEOUT[$1]}" "$1" ;;
    *) echo "unknown tape: $1" >&2; return 2 ;;
  esac
}

selected=("$@")
(( ${#selected[@]} )) || selected=(j1 j2 j3 j4 j5a j5b j5c j5d j5e full)

status=0
for id in "${selected[@]}"; do record_one "$id" || status=1; done
exit "$status"
